version: 2
jobs:
  build:
    docker:
      - image: rust:1.41.0
    steps:
      - checkout
      - run: rustc --version > ~/rust-version
      - restore_cache:
          key: registry
      - restore_cache:
          key: dependencies-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
      - run: cargo build --locked
      - run: cargo run --locked -- tree
      - save_cache:
          key: registry-{{ .BuildNum }}
          paths:
            - /usr/local/cargo/registry/index
      - save_cache:
          key: dependencies-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo/registry/cache
