deps_key: &DEPS_KEY
  key: dependencies-1.40-{{ checksum "Cargo.lock" }}

restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry

save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
      - ~/.cargo/registry/index

restore_deps: &RESTORE_DEPS
  restore_cache:
    <<: *DEPS_KEY

save_deps: &SAVE_DEPS
  save_cache:
    <<: *DEPS_KEY
    paths:
      - target
      - ~/.cargo/registry/cache

version: 2
jobs:
  build:
    docker:
      - image: rust:1.40.0
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends cmake zlib1g-dev
      - <<: *RESTORE_REGISTRY
      - <<: *RESTORE_DEPS
      - run: cargo build --locked
      - run: cargo run --locked -- tree
      - <<: *SAVE_REGISTRY
      - <<: *SAVE_DEPS
